# Generated by Django 5.0.6 on 2024-05-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='duration',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
